- name: Read server.ini
  ansible.windows.slurp:
    src: C:\Program Files (x86)\Trellix\ePolicy Orchestrator\DB\server.ini
  register: server_conf

- name: Decode content
  ansible.builtin.set_fact:
    server_info: "{{ server_conf.content | b64decode }}"

- name: Extract SecureHttpPort value
  ansible.builtin.set_fact:
    secure_http_port: >-
      {{ server_info
         | regex_search('SecureHttpPort=(\\d+)', '\\1')
         | default('') }}

- name: Validate SecureHttpPort
  ansible.builtin.assert:
    that:
      - secure_http_port in ['443', '8443']
    fail_msg: "SecureHttpPort is set to {{ secure_http_port | default('NOT SET') }}, expected 443 or 8443"
    success_msg: "SecureHttpPort correctly set to {{ secure_http_port }}"