I have a task that prints out a property within the first dictionary

    - name: Show Computer Name
      ansible.builtin.debug:
        msg: "{{ cleaned_json[0]['EPOComputerProperties.ComputerName'] }}"

How do I modify this so that it loops through all dictionaries


- name: Show Computer Name (all)
  ansible.builtin.debug:
    msg: "{{ item['EPOComputerProperties.ComputerName'] | default('N/A') }}"
  loop: "{{ cleaned_json }}"



- name: Show Computer Names (one list output)
  ansible.builtin.debug:
    msg: "{{ cleaned_json | map('extract', 'EPOComputerProperties.ComputerName') | list }}"


- name: Show Computer Names (json_query)
  ansible.builtin.debug:
    msg: "{{ cleaned_json | json_query('[].\"EPOComputerProperties.ComputerName\"') }}"
