
Below is the code I have

---

- tags:
    - req2-SDSO-6699
    - SDSO-6699
  block:
    - name: Initialize result tracker
      ansible.builtin.include_tasks: "{{ common_tasks_dir }}/result/init.yaml"

    - name: Call ePO API 
      ansible.windows.win_uri:
        url: "https://localhost:8443/remote/system.find?searchText=&:output=json"
        url_method: GET
        url_username: "{{ epo_user }}"
        url_password: "{{ epo_pass }}"
        force_basic_auth: yes
        validate_certs: no          # self-signed in lab; switch to yes in prod
        return_content: yes
        status_code: 200
      register: epo_response

    - name: Clean and Parse API Response
      # ePO often returns "OK:" before the JSON. We must strip it to get valid JSON.
      ansible.builtin.set_fact:
        # 1. regex_replace strips the leading "OK:"
        # 2. from_json converts the string into an Ansible dictionary/list
        cleaned_json: "{{ epo_response.content | regex_replace('^OK:', '') | trim | from_json }}"

    - name: Display Raw System List
      ansible.builtin.debug:
        var: cleaned_json

    - name: Show keys in first row (sanity check)
      ansible.builtin.debug:
        var: cleaned_json[0]


Here is the terminal result:

TASK [hbss : Show keys in first row (sanity check)] *******************************************************
ok: [192.168.4.46] => {
    "cleaned_json[0]": {
        "EPOBranchNode.AutoID": 4,
        "EPOComputerProperties.CPUSerialNumber": "",
        "EPOComputerProperties.CPUSpeed": 0,
        "EPOComputerProperties.CPUType": "",
        "EPOComputerProperties.ComputerDescription": null,
        "EPOComputerProperties.ComputerName": "192.168.5.11",
        "EPOComputerProperties.DefaultLangID": "",
        "EPOComputerProperties.Description": null,
        "EPOComputerProperties.DomainName": "",
        "EPOComputerProperties.FreeDiskSpace": 0,
        "EPOComputerProperties.FreeMemory": 0,
        "EPOComputerProperties.Free_Space_of_Drive_C": 0,
        "EPOComputerProperties.IPAddress": "",
        "EPOComputerProperties.IPHostName": "",
        "EPOComputerProperties.IPSubnet": null,
        "EPOComputerProperties.IPSubnetMask": null,
        "EPOComputerProperties.IPV4x": null,
        "EPOComputerProperties.IPV6": null,
        "EPOComputerProperties.IPXAddress": "",
        "EPOComputerProperties.IsPortable": -1,
        "EPOComputerProperties.LastAgentHandler": null,
        "EPOComputerProperties.NetAddress": "",
        "EPOComputerProperties.NumOfCPU": 0,
        "EPOComputerProperties.OSBitMode": -1,
        "EPOComputerProperties.OSBuildNum": 0,
        "EPOComputerProperties.OSCsdVersion": "",
        "EPOComputerProperties.OSOEMID": "",
        "EPOComputerProperties.OSPlatform": "",
        "EPOComputerProperties.OSType": "",
        "EPOComputerProperties.OSVersion": "",
        "EPOComputerProperties.ParentID": 1,
        "EPOComputerProperties.SubnetAddress": "",
        "EPOComputerProperties.SubnetMask": "",
        "EPOComputerProperties.TimeZone": "",
        "EPOComputerProperties.TotalDiskSpace": 0,
        "EPOComputerProperties.TotalPhysicalMemory": 0,
        "EPOComputerProperties.Total_Space_of_Drive_C": 0,
        "EPOComputerProperties.UserName": "",
        "EPOComputerProperties.UserProperty1": null,
        "EPOComputerProperties.UserProperty2": null,
        "EPOComputerProperties.UserProperty3": null,
        "EPOComputerProperties.UserProperty4": null,
        "EPOComputerProperties.UserProperty5": null,
        "EPOComputerProperties.UserProperty6": null,
        "EPOComputerProperties.UserProperty7": null,
        "EPOComputerProperties.UserProperty8": null,
        "EPOComputerProperties.Vdi": -1,
        "EPOLeafNode.AgentGUID": null,
        "EPOLeafNode.AgentVersion": null,
        "EPOLeafNode.ExcludedTags": "",
        "EPOLeafNode.LastUpdate": null,
        "EPOLeafNode.ManagedState": 0,
        "EPOLeafNode.Tags": "Win10"
    }
}

TASK [hbss : Display Agent Information] *******************************************************************
skipping: [192.168.4.46]



I can't figure out why the Display Agent Information task skips.  Why does it not show the dictionary?


