I am working with asible and I have target_splunk_host and target_splunk_host_port defined within my inventory.ini file.
when i print out the the server name and port number it works and is what I want but when i use the same variables in the second task it doesn't work.
A coeworker said it may have to do with how jinja interpretas strings. I'm not sure what to do.  


  # We determine inputs.conf is configured if we find a line where "disabled=" set to false
    - name: print out server
      ansible.builtin.debug:
        msg: 'server={{ target_splunk_host }}:{{ target_splunk_host_port }}'

  
  
  # We determine inputs.conf is configured if we find a line where "disabled=" set to false
    - name: Set flag if server degined
      ansible.builtin.set_fact:
        server_is_defined: "{{ server_lines | select('match', '(?i)^server={{ target_splunk_host }}:{{ target_splunk_host_port }}$') | list | length > 0 }}"
