- tags:
    - req1-SDS
  block:
    - name: Initialize result tracker
      ansible.builtin.include_tasks: "{{ common_tasks_dir }}/result/init.yaml"

    - name: Verify Trellix agent is installed
      ansible.windows.win_reg_stat:
        path: 'HKLM:\SOFTWARE\McAfee\Agent'
      register: agent_reg
      failed_when: not agent_reg.exists

    - name: Verify Trellix agent service is running
      ansible.windows.win_service_info:
        name: masvc
      register: agent_service
      failed_when: agent_service.services[0].state != "started"
