- name: Read server.ini
  ansible.windows.slurp:
    src: C:\Program Files (x86)\Trellix\ePolicy Orchestrator\DB\server.ini
  register: server_conf

- name: Decode content
  ansible.builtin.set_fact:
    server_info: "{{ server_conf.content | b64decode }}"

- name: Extract SecureHttpPort value
  ansible.builtin.set_fact:
    secure_http_port: >-
      {{ server_info
         | regex_search('SecureHttpPort=(\\d+)', '\\1')
         | default('') }}

- name: Validate SecureHttpPort
  ansible.builtin.assert:
    that:
      - secure_http_port in ['443', '8443']
    fail_msg: "SecureHttpPort is set to {{ secure_http_port | default('NOT SET') }}, expected 443 or 8443"
    success_msg: "SecureHttpPort correctly set to {{ secure_http_port }}"




- name: Read server.ini
  ansible.windows.slurp:
    src: 'C:\Program Files (x86)\Trellix\ePolicy Orchestrator\DB\server.ini'
  register: server_conf

- name: Decode and Extract Port
  ansible.builtin.set_fact:
    # This regex finds "SecureHttpPort=", ignores spaces, and captures the digits
    secure_port: "{{ (server_conf.content | b64decode | regex_search('SecureHttpPort\\s*=\\s*(\\d+)', '\\1')) | first }}"

- name: Validate SecureHttpPort
  ansible.builtin.assert:
    that:
      - secure_port in ['443', '8443']
    fail_msg: "Validation FAILED: SecureHttpPort is set to '{{ secure_port | default('NOT FOUND') }}'. Expected 443 or 8443."
    success_msg: "Validation PASSED: SecureHttpPort is {{ secure_port }}."


- name: Read server.ini
  ansible.windows.slurp:
    src: 'C:\Program Files (x86)\Trellix\ePolicy Orchestrator\DB\server.ini'
  register: server_conf

- name: Step 1 - Decode file content
  ansible.builtin.set_fact:
    decoded_config: "{{ server_conf['content'] | b64decode }}"

- name: Step 2 - Extract SecureHttpPort value
  ansible.builtin.set_fact:
    # We search for the pattern and capture only the digits (\1)
    # The 'default' filter ensures the playbook doesn't crash if the port isn't found
    secure_port: "{{ (decoded_config | regex_search('SecureHttpPort\\s*=\\s*(\\d+)', '\\1')) | first | default('NOT_FOUND') }}"

- name: Step 3 - Validate the port
  ansible.builtin.assert:
    that:
      - secure_port in ['443', '8443']
    fail_msg: "Validation FAILED: Port found was '{{ secure_port }}'. Expected 443 or 8443."
    success_msg: "Validation PASSED: SecureHttpPort is correctly set to {{ secure_port }}."


