I have an ansible script that is suppose to check if a list of workstations has an Agent installed.  This is what I have.  Am I writting the task correctly?


In my group vars I have
windows_workstations:
  - 192.168.5.11
  - 192.168.4.118


Then in my task yaml I have
---

- tags:
    - req2-SDSO-6699
    - SDSO-6699
  block:
    - name: Initialize result tracker
      ansible.builtin.include_tasks: "{{ common_tasks_dir }}/result/init.yaml"

    - name: Verify Trellix Agent is installed
      ansible.builtin.win_stat:
        path: "C\\Program Files\\McAfee\\Agent"
      delegate_to: "{{ item }}"
      register: mcafee_check
      failed_when: not mcafee_check.stat.exists
      loop: "{{ windows_workstations }}"
      loop_control:
        label: "{{ item }}"

    - name: Record result as passed
      ansible.builtin.include_tasks: "{{ common_tasks_dir }}/result/pass.yaml"

  rescue:
    - name: Display error message
      ansible.builtin.debug:
        msg: "{{ ansible_failed_result }}"

  always:
    - name: Print check result
      ansible.builtin.include_tasks: "{{ common_tasks_dir }}/result/print.yaml"
      vars:
        requirement_text: "The HBSS Software shall implement approved network protocols."
        jira_ticket: SDSO-6699
