- name: Read server.ini
  ansible.builtin.slurp:
    src: "C:/Program Files (x86)/Trellix/ePolicy Orchestrator/Server/conf/server.ini"
  register: server_ini_raw

- name: Decode content
  ansible.builtin.set_fact:
    server_ini_content: "{{ server_ini_raw['content'] | b64decode }}"

- name: Check for SecureHttpPort
  ansible.builtin.debug:
    msg: "SecureHttpPort=8443 FOUND"
  when: "'SecureHttpPort=8443' in server_ini_content"

- name: Fail if port missing
  ansible.builtin.fail:
    msg: "SecureHttpPort=8443 NOT found in server.ini"
  when: "'SecureHttpPort=8443' not in server_ini_content"