---
# playbooks/check-windows-update-gpo.yml
- name: Verify Windows Update is enabled by Group Policy
  hosts: windows
  gather_facts: no
  vars:
    # Treat these AUOptions as acceptable "patching allowed" modes.
    # 2=notify/notify, 3=auto download + notify, 4=auto download + schedule, 5=local admin chooses
    approved_auoptions: [2, 3, 4, 5]

  tasks:
    - name: Check if Windows Update AU policy key exists
      ansible.windows.win_reg_stat:
        path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU
      register: au_key

    - name: Read NoAutoUpdate (if present)
      ansible.windows.win_reg_stat:
        path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU
        name: NoAutoUpdate
      register: noautoupdate_stat
      when: au_key.exists

    - name: Read AUOptions (if present)
      ansible.windows.win_reg_stat:
        path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU
        name: AUOptions
      register: auoptions_stat
      when: au_key.exists

    - name: Determine compliance
      ansible.builtin.set_fact:
        wu_gpo_check:
          key_exists: "{{ au_key.exists | default(false) }}"
          no_auto_update_set: "{{ (noautoupdate_stat.value is defined) }}"
          no_auto_update_value: "{{ (noautoupdate_stat.value | default(None)) }}"
          auoptions_set: "{{ (auoptions_stat.value is defined) }}"
          auoptions_value: "{{ (auoptions_stat.value | default(None)) }}"
          # Compliant when:
          # - key exists (policy configured) AND
          # - NoAutoUpdate is either not set or set to 0 (i.e., NOT disabling updates) AND
          # - AUOptions is either not set (still allows updates) or in approved list.
          compliant: >-
            {{
              (au_key.exists | default(false))
              and (
                    (noautoupdate_stat.value is not defined)
                    or (noautoupdate_stat.value | int == 0)
                  )
              and (
                    (auoptions_stat.value is not defined)
                    or ((auoptions_stat.value | int) in approved_auoptions)
                  )
            }}

    - name: Show Windows Update GPO evaluation
      ansible.builtin.debug:
        var: wu_gpo_check

    - name: Fail if non-compliant
      ansible.builtin.fail:
        msg: >-
          Non-Compliant: Windows Update GPO is not enabling OS patching.
          Details={{ wu_gpo_check }}
      when: not wu_gpo_check.compliant