I want to change my ansible task so that it will print out identity.msg if it exists because sometimes identity has the .msg defined and sometimes it doesn't.
Or make it so it prints out either identity.stdout_lines or identiry.msg depending one exists.

- name: Display log in result
      ansible.builtin.debug:
        msg: "{{ identity.msg }}"
