- become: true
  block:
    - name: Create temporary user {{ test_username }}
      ansible.builtin.user:
        name: "{{ test_username }}"
        state: present
        groups: "{{ user_groups | default('') }}"
        append: true
        password: "{{ user_password | default(lookup('ansible.builtin.password', '/dev/null')) | password_hash('sha512') }}"

    - name: Reset faillock for the temporary user to avoid possible auth failure scenarios
      ansible.builtin.command: "faillock --user {{ test_username }} --reset"
      changed_when: true
      ignore_errors: true
